name: 'Coverage'
on:
  push:
    branches:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: "Test code"
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Run tests
      run: go test ./...

    - name: Calculate Coverage
      id: coverpkg
      uses: ./.
      with:
        token: ${{ github.token }}
        comment: replace
